defaults:
  - _self_
  - checkpoint: last_k
  - data: finetune
  - logger: online
  - logging: default
  - model: finetune
  - optimizer: finetune
  - trainer: finetune
  - decode: default
hydra:  
  output_subdir: null  
  run:  
    dir: .
project_name: vsr_asr_multigpu
experiment_name:
num_workers: 8
fix_seed: True
gpus:
slurm_job_id:
train: False
log_wandb: True
test_on_one_gpu: True