_target_: espnet.nets.pytorch_backend.transformer.encoder.Encoder
idim: ${model.audio_backbone.adim}
attention_dim: 512
attention_heads: 8
linear_units: 2048
num_blocks: 2
input_layer: token_embed
dropout_rate: 0.1
attention_dropout_rate: 0.1
encoder_attn_layer_type: rel_mha
macaron_style: False
use_cnn_module: False
zero_triu: False
a_upsample_ratio: 1
ff_bn_pre: True
post_norm: False
mask_init_type: normal
last_linear: True
odim: ${model.visual_backbone.adim}
